version: '3'

networks:
  nginx-php-mysql-nocde:


services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
        - "8080:80"
    volumes:
        - ./app:/var/www/project
        - .nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php-service
        - mysql-service
    networks:
        - nginx-php-mysql-nocde

  php-service:
  mysql-service:
  node:-service:
